language: python
os: linux
sudo: false
python:
  - "2.7"
  - "3.6"
# command to install dependencies
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
# addons:
#     apt:
#         packages:
#             - libzmq3-dev
#             - sox
install:
    - pip install -U pip setuptools wheel
    - pip install -U -r software/static/requirements.txt
# command to run tests
# script: cd tests && nosetests -v *.py
# script: nosetests -v -w test/
script: true
