---
# DRAFT

- name: Remove nodejs with apt
  apt:
    name: nodejs
    state: absent
    purge: yes
    autoremove: yes
    autoclean: yes
  become: yes

# - name: Setup node apt repo
#   # shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
#   apt_repository:
#     repo: deb https://deb.nodesource.com/node_15.x buster main
#     state: present

- name: Setup node apt repo
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_15.x buster main"
    - "deb-src https://deb.nodesource.com/node_15.x buster main"
  become: yes

# - name: Setup node apt
#   apt_repository:
#     repo: deb-src https://deb.nodesource.com/node_14.x buster main
#     state: present

# - name: Install Nodejs with apt
#   apt:
#     pkg:
#     - nodejs
#     update_cache: yes
- include: tasks/apt.yml
  vars:
    apt_packages: nodejs

- name: Install Archeyjs package globally.
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
    - httpserver
    - archeyjs
  become: yes
