---
# Samba requires ports 137, 138, 139, 445 to be open to function properly
# root: yes
- include: atomics/apt.yml
  vars:
    apt_packages:
      - samba
      - samba-common
      - samba-common-bin
      - avahi-daemon

- name: Create smb.conf
  template:
    src: ../templates/smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0600'
    backup: yes
  become: yes

- name: Ensure Samba is running and set to start on boot.
  service: "name={{ samba_daemon }} state=started enabled=yes"
  become: yes
  vars:
    # debian
    samba_daemon: smbd
