---
# DRAFT
- name: Node setup
  hosts: all
  become: yes

  # pre_tasks:
  # - name: Read pip_packages from yaml file
  #   include_vars: "{{ item }}"
  #   with_first_found:
  #     - "pip_{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"

  # vars:
  #   npm_packages:
  #     - archeyjs
  #     - httpserver

  tasks:
    - name: Remove nodejs with apt
      apt:
        name: nodejs
        state: absent
        purge: yes
        autoremove: yes
        autoclean: yes

    # - name: Setup node apt repo
    #   # shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    #   apt_repository:
    #     repo: deb https://deb.nodesource.com/node_15.x buster main
    #     state: present

    - name: Setup node apt repo
      apt_repository:
        repo: "{{ item }}"
        state: present
      with_items:
        - "deb https://deb.nodesource.com/node_15.x buster main"
        - "deb-src https://deb.nodesource.com/node_15.x buster main"

    # - name: Setup node apt
    #   apt_repository:
    #     repo: deb-src https://deb.nodesource.com/node_14.x buster main
    #     state: present

    - name: Install Nodejs with apt
      apt:
        pkg:
        - nodejs
        update_cache: yes

    - name: Install Archeyjs package globally.
      npm:
        name: "{{ item }}"
        global: yes
      with_items:
        - httpserver
        - archeyjs
