---
# install docker
# root: yes
# upgrade docker: sudo apt upgrade
# remove docker: sudo apt-get purge docker-ce
# deleting leftover images: sudo rm -rf /var/lib/docker

- include: atomics/apt.yml
  vars:
    apt_packages:
      - curl

- name: check docker installed
  shell: "which docker"
  register: result
  ignore_errors: true

- name: Install docker
  shell: |
    curl -sSL https://get.docker.com | sudo -E sh
    "sudo usermod -aG docker {{ ansible_user }}"
  become: yes
  when: # acts ans an AND when put in list; (cond) or (cond) is another way
    - ansible_architecture == "armv7l"
    - result.rc == 0

- include: atomics/pip.yml
  vars:
    pip_packages:
      - docker-compose
