---
# Setup dotfiles
# vars:
# - HOME: user home
# root: false-git clone, true-other

- name: Check for dotfile directory
  stat: path="{{ HOME }}/github/dotfiles"
  register: p

- name: Clone dotfile repo
  git:
    repo: "git@github.com:walchko/dotfiles.git"
    dest: "{{ HOME }}/github/dotfiles"
  become: no
  when: not p.stat.exists

- debug:
    msg: Git repo already cloned
  when: p.stat.isdir is defined and p.stat.isdir

###########################################################
# MOTD
###########################################################
- name: Remove current motd
  file:
    path: /etc/motd
    state: absent
  become: yes

- name: Touch motd so it is an empty file
  file:
    path: /etc/motd
    state: touch
  become: yes

- name: Create a symbolic link to motd
  file:
    src: "{{ HOME }}/github/dotfiles/motd"
    dest: /etc/profile.d/motd.sh
    owner: root
    group: root
    state: link
  become: yes

###########################################################
# Bashrc
###########################################################
- name: Backup current bashrc
  copy:
    src: "{{ HOME }}/.bashrc"
    dest: "{{ HOME }}/.bashrc.old"
    remote_src: yes
  become: no

- name: Remove current bashrc
  file:
    path: "{{ HOME }}/.bashrc"
    state: absent
  become: no

- name: Create a symbolic link to bashrc
  file:
    src: "{{ HOME }}/github/dotfiles/bashrc"
    dest: "{{ HOME }}/.bashrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  become: no
