---
# setup git
# root: apt-yes/git-no
- include: atomics/apt.yml
  vars:
    apt_packages:
      - git

- name: git user
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - {name: user.name, value: walchko}
    - {name: user.email, value: walchko@users.noreply.github.com}
    - {name: push.default, value: simple}
  become: no
