---
# install poetry
# doublecheck it is not already installed
# root: no
- name: check poetry installed
  shell: "which poetry"
  register: result
  ignore_errors: true
  args:
    warn: false

- name: Install poetry
  shell: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
  # args:
  #   warn: false
  become: no
  when: result.rc != 0
