---
# Install python3 if not all ready, also setup venv and poetry

- include: atomics/apt.yml
  vars:
    apt_packages:
      - python3
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python3-venv

- include: atomics/pip.yml
  vars:
    pip_packages:
      - pip
      - setuptools
      - wheel
      - poetry


