---
# Install python3 if not all ready, also setup venv and poetry

- include: atomics/apt.yml
  vars:
    apt_packages:
      - python3
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python3-venv

- include: atomics/pip.yml
  vars:
    pip_packages:
      - pip
      - setuptools
      - wheel


- include: poetry_install.yml
  become: false

    # - name: Install python3 with apt
    #   apt:
    #     pkg: "{{ apt_packages }}"
    #     update_cache: no
    #   become: yes
    #   register: apt_status
    #   until: apt_status is success
    #   delay: 6
    #   retries: 1

    # - name: Install Raspberry Pi packages
    #   apt:
    #     name: picamera[array]
    #     update_cache: no
    #   when: ansible_architecture == "armv7l"

    # - debug: "var=ansible_python"

    # - name: Setup virtualenv and install python modules with pip
    #   pip:
    #     name: "{{ pip_packages }}"
    #     # virtualenv: "{{ ansible_env.HOME }}/venv"
    #     virtualenv: /home/pi/venv
    #     virtualenv_command: /usr/bin/python3 -m venv
    #   register: pip_status
    #   until: pip_status is success
    #   delay: 6
    #   retries: 10

    # - name: Install poetry
    #   shell: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
    #   args:
    #     warn: false
    #   become: no
