---
- include: tasks/atomics/apt.yml
  vars:
    apt_packages:
    - libatlas-base-dev
    - gfortran

- include: python.yml

- include: atomics/pip.yml
  vars:
    pip_packages:
      - numpy
      - opencv_python_headless
      - twine
      - psutil
      - pytest
      - simplejson
      - colorama
      - pyserial
