---
# configure ssh keys and config
# root: no
# vars:
# - HOME
# - public_key
# - private_key

# - debug: "var=public_key"
# - debug: "var=private_key"
# - debug: "var=ansible_python_interpreter"

- name: Template public key
  template:
    src: ../templates/key.j2
    dest: "{{ HOME }}/.ssh/id_ed25519.pub"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  vars:
    ssh_key: "{{ public_key }}"

- name: Template for private key
  template:
    src: ../templates/key.j2
    dest: "{{ HOME }}/.ssh/id_ed25519"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  vars:
    ssh_key: "{{ private_key }}"

- name: Template ssh conf
  template:
    src: ../templates/ssh_config.j2
    dest: "{{ HOME }}/.ssh/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
