---
# update APT packages
# root: yes

- name: Update cache and system packages
  apt:
    upgrade: yes
    update_cache: yes
  become: yes

- name: Auto clean up and auto remove
  apt:
    autoclean: yes
    autoremove: yes
  become: yes
