---
# Set Pi password
# vars:
# - ansible_user: user name
# - newpassword: user password
# root: yes
- name: Change Password
  become: yes
  user:
    name: "{{ ansible_user }}"  # pi
    # pip install passlib
    # string: convert int or floats
    # trim: remove '\n'
    password: "{{ newpassword | string | trim | password_hash('sha512') }}"
