---
- name: Python setup
  hosts: all
  become: no

  # pre_tasks:
  # - name: Read pip_packages from yaml file
  #   include_vars: "{{ item }}"
  #   with_first_found:
  #     - "pip_{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"

  vars:
    pip_packages:
      - pip
      - setuptools
      - wheel
      - numpy
      - opencv_python_headless
      - twine
      - psutil
      - pytest
      - simplejson
      - colorama
      - pyserial
      - picamera[array]

  tasks:

    - name: Install python3 with apt
      apt:
        pkg:
        - python3
        - python3-dev
        - python3-pip
        - python3-venv
        update_cache: no
      become: yes

    - name: Setup virtualenv and install python modules with pip
      pip:
        name: "{{ pip_packages }}"
        virtualenv: "{{ ansible_env.HOME }}/venv"
        virtualenv_command: python3 -m venv
      become: no

    - name: Install poetry
      become: no
      shell: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
