# Samba requires ports 137, 138, 139, 445 to be open to function properly
---
- name: Install and setup samba
  hosts: all
  become: yes

  vars:
    # debian
    samba_daemon: smbd
    apt_packages:
      - samba
      - samba-common
      - avahi-daemon

  tasks:
    - name: Install packages
      apt:
        upgrade: "{{ apt_packages }}"
        update_cache: yes

    # - name: Update smb.conf
    #   blockinfile:
    #     path: /etc/samba/smb.conf
    #     backup: yes
    #     block: |
    #       [{{ ansible_nodename }}]
    #         comment = Home Directories
    #         browseable = yes
    #         read only = no
    #         create mask = 0700
    #         directory mask = 0700
    #         valid users = %S
    #         path=/home/%S

    - name: Update sshd configuration safely, avoid locking yourself out
      template:
        src: templates/smb.conf.j2
        dest: /etc/samba/smb.conf
        owner: root
        group: root
        mode: '0600'
        backup: yes

    - name: Ensure Samba is running and set to start on boot.
      service: "name={{ samba_daemon }} state=started enabled=yes"
