---
version: '3'

services:
  raspberrypi:
    build: .
    image: walchko/raspberrypi:0.1
    container_name: raspberrypi
    ports:
      # - "443:443/tcp"
      - "2222:22/tcp"

    environment:
      TZ: 'America/Chicago'
      # VIRTUAL_HOST: debian.local
      # ServerIP: 10.0.1.7
